# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Magnesium"
license = "MIT"
licenselink = "https://github.com/milligramme/magnesium/blob/master/LICENSE.md"
description = "PureCSS based theme"
homepage = "https://github.com/milligramme/magnesium"
tags = ["blog", "responsive"]
features = ["blog", "responsive", "search"]
min_version = 0.17

[author]
  name = "milligramme"
  homepage = "https://github.com/milligramme"
