# baseurl = "https://milligramme.gitlab.io/note/"
baseurl = "https://milligramme.github.io/"
languageCode = "ja-JP"
title = "mg:note"
theme = "magnesium"

copyright = "<i class='fa fa-copyright fa-fw'></i> 2009-2017. All rights reserved."
canonifyurls = true
hasCJKLanguage = true
paginate = 10

googleAnalytics = "UA-20033906-2"
disqusShortname = "mgnote"

[indexes]
  tag = "tags"

[params]
  author = "milligramme"

  # Shown in the home page
  subtitle = "ちらしのうらがきです"
  brand = "<i class='fa fa-dot-circle-o'></i> :note"
  
  # CSS name for highlight.js https://highlightjs.org/static/demo/
  highlightjs = "atom-one-light"
  dateFormat = "2006-01-02 Mon."

  [params.dev]
    # Local working dir to edit with [TextMate](https://macromates.com/)
    # This works under Development Mode.(env HUGO_ENV=DEV)
    workingdir = "~/play/milligramme.hugo/content"

  [params.social]
    twitter = "milligramme"
    facebook = ""
    googleplus = ""
    tumblr = "milligramme"
    pinterest = "milligramme"
    stackoverflow = "1536789"
    github = "milligramme"
    bitbucket = ""
    gitlab = ""
    instagram = ""
    flickr = ""
    linkedin = ""
    vimeo = "milligramme"
    soundcloud = "milligramme"
    lastfm = ""
    youtube = ""
    pinboard = "milligramme"
    slideshare = ""
    speakerdeck = ""
    amazon = "amzn.asia/5DvPEOK"
    
  [params.adsense]
    mobile_anchor = "adsense/mobile_anchor_adv"
    responsive1 = "adsense/responsive_adv1"
    responsive2 = "adsense/responsive_adv2"
  
[menu]
  [[menu.main]]
    name = "home"
    pre = "<i class='fa fa-bath fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "posts"
    pre = "<i class='fa fa-file-text-o fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 2
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "about"
    pre = "<i class='fa fa-smile-o fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"

