baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "Magnesium Demo"
languageCode = "en-us"
theme = "magnesium"

copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 3

[params]

  author = "milligramme"

  # Shown in the home page
  subtitle = "Subtitle"
  brand = "🔥:magnesium"
  googleAnalytics = "Your Google Analytics tracking ID"
  # CSS name for highlight.js https://highlightjs.org/static/demo/
  highlightjs = "atom-one-light"
  dateFormat = "2006-01-02 15:04"
  
  # Local working dir for edit with TextMate
  # This work under Development Mode
  # workingdir = "/path/to/hugo/content"

[indexes]
  tag = "tags"
  
[menu]
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 1
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
    
[social]
  twitter = ""
  facebook = ""
  googleplus = ""
  tumblr = ""
  pinterest = ""
  stackoverflow = ""
  github = ""
  bitbucket = ""
  gitlab = ""
  instagram = ""
  flickr = ""
  linkedin = ""
  vimeo = ""
  soundcloud = ""
  lastfm = ""
  youtube = ""
  pinboard = ""
  slideshare = ""
  speakerdeck = ""
  